# Server config
server:
  port: ${PORT:8765}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: api-gateway

  cloud:
    gateway: 
      routes:
        - id: product-service
          uri: http://localhost:8081/
          predicates:
            - Path=/products/**
        - id: category-service
          uri: http://localhost:8082/
          predicates:
            - Path=/categories/**
        - id: theme-service
          uri: http://localhost:8083/
          predicates:
            - Path=/themes/**

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
    registerWithEureka: false
    fetchRegistry: false

# Ribbon config
ribbon:
  eureka:
    enabled: true

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false
